### ISSUE TITLE
npm ERR! 504 Gateway Time-out: async-validator@https://registry.npmjs.org/async-validator/-/async-validator-1.8.2.tgz

### ISSUE THREAD

**Issue by marioaldayuz** [yiminghe/async-validator#103]
Receiving this error when trying to install via NPM

**Comment by LordotU** [comment]
For yarn registry (https://registry.yarnpkg.com/async-validator/-/async-validator-1.8.2.tgz) it is the same...

**Comment by BigRoma** [comment]
It's work correct, now. @marioaldayuz you can close issue.

**Comment by thatneat** [comment]
possibly related issue on npm:
`404 Not Found: async-validator@https://registry.npmjs.org/async-validator/-/async-validator-1.8.2.tgz`

**Comment by xjliang2007** [comment]
@thatneat  I encounter the same issue as you did, did you figure out the reason?

**Comment by xjliang2007** [comment]
@thatneat  I try to use a Chinese mirror of npm, then use cnpm to install again, and it works successfully. I guess the central npm module store may have some bugs.

the link to refer : https://npm.taobao.org/
just need two step : 
1. install cnpm as a module :  npm install -g cnpm --registry=https://registry.npm.taobao.org  
2. use cnpm to install modules : cnpm install [module_name]

**Comment by marioaldayuz** [comment]
Fixed

**Comment by thatneat** [comment]
Thanks!

**Comment by siordache** [comment]
I'd like to see this issue reopened.
We have a workaround, but `npm i async-validator` still doesn't work.

**Comment by siordache** [comment]
The problem has been fixed:
https://github.com/npm/registry/issues/329#issuecomment-392289993

**Comment by ygj6** [comment]
solved, close
