### ISSUE TITLE
1.8.2版本 unpublish ？

### ISSUE THREAD

**Issue by tangjinzhou** [yiminghe/async-validator#105]
404 Not Found: async-validator@https://registry.npmjs.org/async-validator/-/async-validator-1.8.2.tgz

**Comment by ke1vin666** [comment]
我这打包失败。。。请问lz解决没

**Comment by Adam-Burke** [comment]
This is breaking my app. Please fix or provide workaround

**Comment by dobromir-hristov** [comment]
Oh things are gonna get messy now :) Just got this too.

**Comment by indrajit-rathod** [comment]
npm ERR! code E404
npm ERR! 404 Not Found: async-validator@https://registry.npmjs.org/async-validator/-/async-validator-1.8.2.tgz
Is there a workaround to solve this issue ?

**Comment by afc163** [comment]
+1

**Comment by afc163** [comment]
https://github.com/npm/registry/issues/329#issuecomment-392231959

**Comment by wu-sheng** [comment]
+1 Facing the same issue, at Apache SkyWalking
