### ISSUE TITLE
如何清空验证产生的错误信息,重置成初始状态

### ISSUE THREAD

**Issue by itlixiaolong** [yiminghe/async-validator#110]

**Comment by BoleLee** [comment]
@itlixiaolong 请问是否有找到相关API实现重置错误信息？

**Comment by itlixiaolong** [comment]
我用的是elementui的 form组件里面有清空api,  this.$refs[formName].resetFields(),不知道对你有没有帮助

**Comment by ygj6** [comment]
So the problem is solved,issue closed.
