### ISSUE TITLE
How to do the inverse of enum

### ISSUE THREAD

**Issue by ray-4dvw** [yiminghe/async-validator#122]
I wanna validate if the input is unique from the list that I have.     

Example:   I have `enum: ['aa', 'bb', 'cc']`,    and if the input is either  'aa', 'bb' or  'cc' => validation fails.   

Thanks

**Comment by ray-4dvw** [comment]
sorry, Im new to this plugin,  solved by using custom validator.

**Comment by JinShng** [comment]
Is this problem solved? I also encountered the same problem, the version used is 1.10
