### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by ankitbko** [yiminghe/async-validator#150]
Missing d.ts file for typescript. Are you planning on supporting typescript?

**Comment by MrErHu** [comment]
The feature is important

**Comment by ryerh** [comment]
@yiminghe Got any plan on this feature? Are you gonna put declaration files in this project or DefinitelyTyped. I can help.

**Comment by raphaelsoul** [comment]
one more thing is 

some newly updated typescript versions will throw error when `throw []`(throw a non error type).

**Comment by yiminghe** [comment]
welcome pr

**Comment by iamdhj** [comment]
had add `d.ts` file #185

**Comment by ygj6** [comment]
PR merged,close.
