### ISSUE TITLE
你好，请问自定义验证的时候(rule, value, callback) =>{}可以传参数吗？

### ISSUE THREAD

**Issue by zouhuigang** [yiminghe/async-validator#156]
表单绑定:
:prop="'items.' + index + '.consume_num'" 
:prop="'items.' + index + '.buy_num'" 
rule中的值是:
field: "items.1.buy_num"
fullField: "items.1.buy_num"
trigger: "blur"
type: "string"

在循环的时候需要同时验证,同一行中，其他input的参数是否合法。不传个index值，我只能从field中分割出的index的值么？

**Comment by LindsyT** [comment]
你解决了吗，我也在用动态绑定prop值，但是validator还是无法监测value改变

**Comment by qw52655265** [comment]
同样遇到这个问题，这是不可以加自定义参数吗？大大有找到什么好的解决办法了么？同样需要一个自定义的index @zouhuigang
