### ISSUE TITLE
Please don't append useless args to the output message

### ISSUE THREAD

**Issue by lianzhao** [yiminghe/async-validator#167]
I wanted to customize message from 
```javascript
    types: {
      integer: '%s is not an %s',
    },
```
to
```javascript
    types: {
      integer: '%s必须是整数',
    },
```

But the output message was `myField 必须是整数 integer`. I found that `async-validator` appends args to the output message even if it was useless?
https://github.com/yiminghe/async-validator/blob/08d67b8300153783fe61d542119baa84e51b4407/src/util.js#L63
```javascript
    for (let arg = args[i]; i < len; arg = args[++i]) {
      str += ` ${arg}`;
    }
```

**Comment by ygj6** [comment]
If you want to customize messages, you can refer to the following examples instead of modifying the source code.
https://github.com/yiminghe/async-validator#messages
or
https://github.com/yiminghe/async-validator/blob/master/__tests__/messages.spec.js
