### ISSUE TITLE
正则校验的问题

### ISSUE THREAD

**Issue by WhatAKitty** [yiminghe/async-validator#17]
`{ type: 'regexp', pattern: /^1[0-9]{10}$|^[569][0-9]{7}$/,  message: '请填写正确的手机号码' },`

校验的写法有问题吗？校验没有任何效果

**Comment by tolg** [comment]
去掉type: 'regexp'，这个东西是验证被验证内容本身是否是正则的。

**Comment by WhatAKitty** [comment]
@tolg 好的，谢谢！

**Comment by chou0728** [comment]
{ type: 'string', pattern: /^1[0-9]{10}$|^[569][0-9]{7}$/, message: '请填写正确的手机号码' }

type 需要是string才會起作用

**Comment by asins** [comment]
> { type: 'string', pattern: /^1[0-9]{10}$|^[569][0-9]{7}$/, message: '请填写正确的手机号码' }
> 
> type 需要是string才會起作用

type为string是默认的，所以可以不写
