### ISSUE TITLE
1.12.0 新版编译工具引入了破坏性更改

### ISSUE THREAD

**Issue by nuintun** [yiminghe/async-validator#174]
```js
const Validator = require('async-validator');
```

现在无法运行，要使用：

```js
const Validator = require('async-validator').default;
```

**Comment by a62527776a** [comment]
我现在用的是egg-y-validator 他依赖的async-validator 我已经不知道该怎么办了

**Comment by nuintun** [comment]
@yiminghe

**Comment by nuintun** [comment]
@a62527776a 无解，要么换库，要么等 `async-validator` 更新 或者 `egg-y-validator` 更新，这次更新违背了 `semver` !

**Comment by a62527776a** [comment]
> @a62527776a 无解，要么换库，要么等 `async-validator` 更新 或者 `egg-y-validator` 更新，这次更新违背了 `semver` !

我暂时将egg-y-validator放到了项目内 并把async-validator的版本号写死为1.8.0

**Comment by yiminghe** [comment]
sorry, 1.12.2(1.11.5) published
