### ISSUE TITLE
Error in created hook: "TypeError: schema is not a constructor

### ISSUE THREAD

**Issue by mei2015** [yiminghe/async-validator#178]
按照 你给的例子 出现这个错误怎么回事啊啊

**Comment by xsbear** [comment]
`const { default: Schema } = require('async-validator')`
用这个可以暂时解决

**Comment by mei2015** [comment]
> `const { default: Schema } = require('async-validator')`
> 用这个可以暂时解决

这个是他插件写的问题吗

**Comment by xsbear** [comment]
> > `const { default: Schema } = require('async-validator')`
> > 用这个可以暂时解决
> 
> 这个是他插件写的问题吗

源码用了 `export default`， node dist版本里被编译成了` exports.default = Schema`, 所以引入时需要访问default属性

**Comment by mei2015** [comment]
> > > `const { default: Schema } = require('async-validator')`
> > > 用这个可以暂时解决
> > 
> > 
> > 这个是他插件写的问题吗
> 
> 源码用了 `export default`， node dist版本里被编译成了` exports.default = Schema`, 所以引入时需要访问default属性

哦哦谢谢

**Comment by Rudy24** [comment]
上面都是require写法，如果是import写法可以采用下面方法
```javascript
import Schema from "async-validator";
const { default: Schema } = validator
const validator = new Schema(rules)
```
