### ISSUE TITLE
校验通过，但是没有触发成功回调

### ISSUE THREAD

**Issue by Stpcurry30** [yiminghe/async-validator#187]
代码如下，忘指点：
`confirm() {
      let descriptor = {
        // 某个表单项的校验，单个可传对象，多个传入数组
        phone: {
          required: true,
          message: "手机号码不能为空"
        },
        testVali: [
          {
            required: true,
            message: "test不能为空"
          },
          {
            validator: (rule, value) => {
              let reg = /^\d{11}$/g;
              if (!reg.test(value)) {
                return new Error("testVali必须是11位数字！");
              }
            }
          }
        ]
      };
      let validator = new AsyncValidator(descriptor);
      let form = {
        phone: this.formData.phone,
        testVali: this.formData.testVali
      };
      // firstFields: true -- 同个字段多个校验规则，只处理第一个校验规则
      validator
        .validate(form, { firstFields: true }, errors => {
          if (errors) {
            // validation failed, errors is an array of all errors
            // fields is an object keyed by field name with an array of
            // errors per field
            alert(JSON.stringify(errors));
            // this.handleErrors(errors);
            // return;
          }
          // validation passed
          alert(222);
          // 调用发送请求
        })
        .then(() => {
          // 调用发送请求
          alert(2222222);
        });
    }`
如上，表单校验通过后，alert(222)和alert(2222222)都没有触发，请问是什么问题呢

**Comment by Stpcurry30** [comment]
`let descriptor = {`
    `phone: {
          required: true,
          message: "手机号码不能为空"
        },`
    `testVali: [
          {
            required: true,
            message: "test不能为空"
          },
          {
            validator: (rule, value) => {
              let reg = /^\d{11}$/g;
              if (!reg.test(value)) {
                return new Error("testVali必须是11位数字！");
              }
            }
          }
        ]`
`};`
`let validator = new AsyncValidator(descriptor);`
`let form = {
        phone: this.formData.phone,
        testVali: this.formData.testVali
      };`
`validator
        .validate(form, { firstFields: true }, errors => {`
`if (errors) {`
`alert(JSON.stringify(errors));`
`}`
`// validation passed`
`alert(222);`
`}).then(() => {`
`alert(2222222);`
`});`

**Comment by ygj6** [comment]
> 如上，表单校验通过后，alert(222)和alert(2222222)都没有触发，请问是什么问题呢

In your code, the validator lacks the return value when the check passes, which prevents cb () from being called in the source code. I modified it a bit and it works
```
let descriptor = {
  phone: { required: true, message: "手机号码不能为空" },
  testVali: {
    required: true,
    message: "test不能为空",
    validator: (rule, value) => {
      let reg = /^\d{11}$/g;
      if (!reg.test(value)) {
        return new Error("testVali必须是11位数字！");
      }
      return true
    }
  }
};
let validator = new AsyncValidator(descriptor);
let form = { phone: 11111111111, testVali: 11111111111};

validator.validate(form, { firstFields: true }, errors => {
  if (errors) {
    console.log(JSON.stringify(errors));
  }
  // validation passed
  console.log(222);
}).then(() => {
  console.log(2222222);
}).catch(() => {
  console.log(33333333)
});
```

**Comment by ygj6** [comment]
Closed.
