### ISSUE TITLE
bug: dateObject.getTime()

### ISSUE THREAD

**Issue by itwarlock** [yiminghe/async-validator#195]
date.js 
line:36 . 
fixe it please:
if (dateObject) {
        //_rule2['default'].range(rule, dateObject.getTime(), source, errors, options);
          _rule2['default'].range(rule, (new Date(dateObject)).getTime(), source, errors, options);
      }

**Comment by ygj6** [comment]
reference #196 discussion.

https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Date
```
时间戳字符串
dateString
表示日期的字符串值。该字符串应该能被 Date.parse() 正确方法识别（即符合 IETF-compliant RFC 2822 timestamps 或 version of ISO8601）。
注意: 由于浏览器之间的差异与不一致性，强烈不推荐使用Date构造函数来解析日期字符串 (或使用与其等价的Date.parse)。对 RFC 2822 格式的日期仅有约定俗称的支持。 对 ISO 8601 格式的支持中，仅有日期的串 (例如 "1970-01-01") 会被处理为 UTC 而不是本地时间，与其他格式的串的处理不同。
```
