### ISSUE TITLE
asyncValidator  异步验证怎么防抖 debounce

### ISSUE THREAD

**Issue by maxmeng93** [yiminghe/async-validator#201]
asyncValidator  异步验证怎么防抖 debounce

使用 antd ，对 FormItem 做异步验证时，自定义验证器，怎么做防抖？参数应该怎么传。

**Comment by afc163** [comment]
怎么解决的？

**Comment by jimmycarry** [comment]
我们项目中，可以用类似 rxjs 在http上做防抖，而不是在这个库本身，当然这个库如果有防抖就更好了

**Comment by zhytang** [comment]
发现了使用debounce的bug，async-validator1.8.5，通过改util.js来解决的
