### ISSUE TITLE
类型为 number 数字验证不通过的BUG

### ISSUE THREAD

**Issue by fengcms** [yiminghe/async-validator#21]
```html
<template>
<el-form ref="form" :model="form" :rules="rules" label-width="100px">
        <el-form-item label="提现金额" prop="money">
          <el-input v-model="form.money"></el-input>
        </el-form-item>
      </el-form>
</template>
<script>
export default {
  data() {
    return {
      form:{
        money:null,
      },
      rules: {
        money: [
          { required: true, message: '请输入提现金额', trigger: 'blur' },
          { type:"number", message: '请输入正确的提现金额', trigger: 'blur' }
        ]
      }
    }
  }
</script>
```
输入数字校验不正确，提示 请输入正确的提现金额

修改源码`lib/rule/type.js`第56行为
```js
return typeof +value === 'number';
```
则可以通过验证。

**Comment by Ben07** [comment]
input中获取的值是string类型，导致type不符。

**Comment by bailnl** [comment]
transfrom

**Comment by microyulive** [comment]
我也遇到了 =。=。。。

**Comment by gaoyoubo** [comment]
+1 同样被这个问题困扰。

**Comment by fengcms** [comment]
<el-input v-model="form.money" type="number></el-input>
这样可以解决，但是input就会出现上下箭头，可以用css去掉。

**Comment by ufohjl** [comment]
我感觉这个应该修复下 
这不是很符合直觉

**Comment by kivan** [comment]
数字类型的验证需要在 v-model 处加上 .number 的修饰符，这是 Vue 自身提供的用于将绑定值转化为 number 类型的修饰符。

**Comment by walkerqiao** [comment]
的确，对于number的验证是不通过的， 修复下好些。

**Comment by BlueGene89** [comment]
我vue 2.2.4 也是这个问题

**Comment by frankxin** [comment]
在自定义input类型中，貌似 type=number 这个自定义属性会有问题，会触发某些toNumber（parseFloat）的机制，不是很懂，求解

**Comment by lcoder** [comment]
可以用`InputNumber `组件，默认就是数字类型了

**Comment by PaulKim725** [comment]
和上面一样的问题。

规则设置：
{ required: true, message: '请输入提现金额', trigger: 'blur' },
{ type:"number", message: '请输入正确的提现金额', trigger: 'blur' }

在打开修改页面后，直接点击提交会提示“请输入提现金额”，控制台给出信息是not a string。应该是规则没有设置type默认是字符串的问题。

在修改输入框中值后会提示not a number。应该是修改后input内值获得默认是string类型的值的问题。

**Comment by byc233518** [comment]
现在也还是有这个问题, 并且现在不能直接设置 input type=number, 会直接报prop的错

**Comment by For-me** [comment]
{type:'number',required:true,message:'请输入合法的优惠金额',trigger:'blur'}组合v-model.number是能解决纯数字验证不通过的问题，但是组合number+string也会被通过。所以还是内部验证有问题的

**Comment by qmdx** [comment]
@yiminghe   这是一个大坑 ， 这么多人遇到了 希望作者尽快修复， 辛苦了！

**Comment by zimplexing** [comment]
@kivan 加上.number修饰符之后 向123asb 这种直接转成了123 还是没办法很好的解决这个问题

**Comment by dreamcatcher081210** [comment]
各位，还是写validator吧。
`const validateNumber = (rule, value, callback) => {
                if (!value) {
                    return callback(new Error('不能为空'));
                }
                if (!Number.isInteger(parseInt(value))) {
                    callback(new Error('请输入数字值'));
                }
                if(value < 0 || value > 99999999) {
                    callback(new Error('输入值得区间0~99999999'));
                }
                callback();
            };`

**Comment by dreamcatcher081210** [comment]
各位还是写validator吧。

`const validateNumber = (rule, value, callback) => {`
`                if (!value) {`
`                    return callback(new Error('不能为空'));`
`                }`
`                if (!Number.isInteger(parseInt(value))) {`
`                    callback(new Error('请输入数字值'));`
`                }`
`                if(value < 0 || value > 99999999) {`
`                    callback(new Error('输入区间0~99999999'));`
`                }`
`                callback();`
`            };`

**Comment by axhello** [comment]
我发现去掉`trigger:'blur'`就可以解决了诶，这是bug么?

**Comment by wweggplant** [comment]
使用lodash的toNumber可以解决这个问题 

```
{
    type: 'number',
     trigger: 'blur',
     transform(value) {
         return _.toNumber(value);
     },
}
```

**Comment by Chinese1904** [comment]
Wish you guys spoke English in here lol I am coming across the same issue I believe. Is this able to get fixed in core? Or will we need  a workaround?

**Comment by guohuihot** [comment]
v-model.number

**Comment by rubaiet** [comment]
1. Add **number** on v-model for the input, so it will look like `v-model.number` 
2. Add rules for the input
`{ type: 'integer', trigger: 'blur', min: 1, max: 100000, trigger: 'change'}`

**Comment by NoDocCat** [comment]
The issue start at 2016-11, now is 2019-06.
bug? feature?

**Comment by storesbuzz** [comment]
Having same issue, Number validation doesn't work. Even when i add number as input it still display error message. Anyone has got any solution?

**Comment by mjfwebb** [comment]
You can transform the type to number directly in the rule:

https://github.com/yiminghe/async-validator/blob/b3ed037ebc327defc78ac127db0f5de54d7cad0a/__tests__/number.spec.js#L79

```
{
  type: "number",
  transform: Number
},
```

**Comment by DamonDBT** [comment]
我重装了NPM 环境，重新更新依赖包，居然可以了，代码没做任何修改。

**Comment by YujiaCheng1996** [comment]
使用vue正常情况下呢就v-model.number解决了，但是项目里用的是vue3 + element-plus + tsx，tsx没有对.number修饰符的任何支持，所以尝试各种方法都不顶用，只能去掉校验。

**Comment by crazyair** [comment]
https://github.com/react-component/async-validator/pull/2
