### ISSUE TITLE
type为any类型报错

### ISSUE THREAD

**Issue by teshoudong** [yiminghe/async-validator#212]
![image](https://user-images.githubusercontent.com/24988831/71573680-2355e100-2b20-11ea-82fd-a6103d2faa4b.png)
设置type为any类型后报错

**Comment by ygj6** [comment]
Can you provide some code that can be reproduced？

**Comment by skyfore** [comment]
```javascript
{
  pattern: new RegExp()
}
```

use it for setting `any` type
通过设置这个实现 any 类型的支持

**Comment by teshoudong** [comment]
我看3.2.x已经支持并且没报错了，关闭这个issue
