### ISSUE TITLE
提供类似 transform 但不修改原属性的 map 处理

### ISSUE THREAD

**Issue by jaredleechn** [yiminghe/async-validator#29]
https://github.com/yiminghe/async-validator#transform

rules 数组的每一个 item 想要的转化操作可能是不相同的，如果是有修改原值的 transform，还要把之前的操作给 de-transform 回去，能否提供一个 map 处理，作用域只保留在是 rules 当前的 item

**Comment by ygj6** [comment]
https://github.com/yiminghe/async-validator/issues/202#issuecomment-557960694
