### ISSUE TITLE
Async Validation Error

### ISSUE THREAD

**Issue by Wlisfes** [yiminghe/async-validator#324]
## 使用async-validator时出现报错
![image](https://user-images.githubusercontent.com/32263302/205201657-9238ee91-d765-41a4-822e-dc6f403943bb.png)
![image](https://user-images.githubusercontent.com/32263302/205201680-47cc69bd-fff2-49a6-ae51-026abd73caeb.png)

**Comment by kiccer** [comment]
请问问题解决了吗？我也遇到了

**Comment by Z-dust** [comment]
me too!!!!!!!!

**Comment by xw5** [comment]
me too!!!

**Comment by xxxace** [comment]
```
    try {
      await validator.validate(r.value || {})
    } catch (e: any) {
      if (e.errors) e.errors.forEach((error) => errors.push(Object.assign({ index: 0 }, error)))
    }
```
