### ISSUE TITLE
如何动态验证for出来的select呢

### ISSUE THREAD

**Issue by bihongbin3027** [yiminghe/async-validator#33]
![ms_a ef8xko68f r5 nqhu](https://cloud.githubusercontent.com/assets/15045200/23790508/491dd944-05ba-11e7-8d43-2b06f6e28828.png)
请问这种如何验证呢

**Comment by wq0923** [comment]
vm.$set(vm.addRule,e.xx,[{ required: true, message: '', trigger: 'blur' }]);
