### ISSUE TITLE
transform 直接返回 value 交互不一致

### ISSUE THREAD

**Issue by crazyair** [yiminghe/async-validator#339]
https://stackblitz.com/edit/react-r9ktbk?file=demo.tsx
点击 `Sumbit` 第一个 `Gender` 会报错

**Comment by crazyair** [comment]
有人吗

**Comment by wangz-code** [comment]
我猜测
看源码getType 这里获取数据类型, 如果未指定默认type则默为 "string"   你的代码未指定type且你的数据为数字类型, 所以效验的时候是按照字符串处理, 但是你通过 transform 返回一个数字 变相把数据转变成数字了, 原有的逻辑走不通了,    

第二个没问题是因为 没指定transform 也没指定 type  数据全程按照 "string"  处理所以没问题

<img width="780" alt="image" src="https://github.com/yiminghe/async-validator/assets/8155037/995e0202-b449-478b-942f-43dac41b2644">

**Comment by crazyair** [comment]
> 我猜测 看源码getType 这里获取数据类型, 如果未指定默认type则默为 "string" 你的代码未指定type且你的数据为数字类型, 所以效验的时候是按照字符串处理, 但是你通过 transform 返回一个数字 变相把数据转变成数字了, 原有的逻辑走不通了,
> 
> 第二个没问题是因为 没指定transform 也没指定 type 数据全程按照 "string" 处理所以没问题
> 
> <img alt="image" width="780" src="https://private-user-images.githubusercontent.com/8155037/314409918-995e0202-b449-478b-942f-43dac41b2644.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5MjA2ODMsIm5iZiI6MTcxMDkyMDM4MywicGF0aCI6Ii84MTU1MDM3LzMxNDQwOTkxOC05OTVlMDIwMi1iNDQ5LTQ3OGItOTQyZi00M2RhYzQxYjI2NDQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjBUMDczOTQzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmM1ZGJlZmVjNTMwZjE5NmFmMjlmNjkzNzQwMzViNjZiYTk2ZDExMDAxNTg5YmNiZTE4YzEwYjcwYjRkYzYyYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.fqoQckmjqa8cwLbHLgq5FNZ42zN7DzVK91INEUsPz3A">

问题很容易找，就是看修不修吧

**Comment by crazyair** [comment]
> 我猜测 看源码getType 这里获取数据类型, 如果未指定默认type则默为 "string" 你的代码未指定type且你的数据为数字类型, 所以效验的时候是按照字符串处理, 但是你通过 transform 返回一个数字 变相把数据转变成数字了, 原有的逻辑走不通了,
> 
> 第二个没问题是因为 没指定transform 也没指定 type 数据全程按照 "string" 处理所以没问题
> 

另外，type 2个都没指定，按理说 type 默认值是一样的，这里结果不一样就是 bug

**Comment by wangz-code** [comment]
> > 我猜测 看源码getType 这里获取数据类型, 如果未指定默认type则默为 "string" 你的代码未指定type且你的数据为数字类型, 所以效验的时候是按照字符串处理, 但是你通过 transform 返回一个数字 变相把数据转变成数字了, 原有的逻辑走不通了,
> > 第二个没问题是因为 没指定transform 也没指定 type 数据全程按照 "string" 处理所以没问题
> 
> 另外，type 2个都没指定，按理说 type 默认值是一样的，这里结果不一样就是 bug

这个库看起来很久没人维护了, 看作者最近也有活跃但这个库却没任何回应, 不清楚是什么原因或许是放弃了吧
