### ISSUE TITLE
Leak environment variable information

### ISSUE THREAD

**Issue by QuyXuanBui** [yiminghe/async-validator#345]
In `util.ts` file:
![Screenshot from 2024-05-06 16-33-51](https://github.com/yiminghe/async-validator/assets/95370045/a4166092-0c8b-4b06-8644-eb9a63796a62)

Use `process.env` leads to leaking environment variable information when view page source 

![Screenshot from 2024-05-06 16-34-19](https://github.com/yiminghe/async-validator/assets/95370045/1bbc801d-323c-47f0-93b9-c4ba9b4c514a)

**Comment by lllllxt** [comment]
我们项目是通过 require('async-validator') 引用的，实际是用了/dist-web/index.js 
这是npm上的/dist-web/index.js代码 还是有直接使用process.env

![Image](https://github.com/user-attachments/assets/2114a810-4888-4eab-9aef-197965b49291)
