### ISSUE TITLE
rule function 里面如何绑定 this，以便能够与外部组件的props比较

### ISSUE THREAD

**Issue by TangMonk** [yiminghe/async-validator#36]
```
        {getFieldDecorator('price', {
            rules: [{
              required: true,
              message: '必填'
            },{
              type: 'number',
              message: '请输入数字'
            },{
              validator(rule, value, callback){
                if(value<20){
                  callback(['出金金额必须大于或等于20'])
                }else if(value < this.props.balance_price){  // 这里
                  callback(['你的余额不足'])
                }
                else{
                  callback([])
                }
              }
            }]
          })(
            <InputNumber/>
          )}
```

**Comment by kelvshi** [comment]
试着将自定义的函数写在外面，然后在传给对应的校验字段，例如：基于Vue的一个例子
`export default {
        data () {

            const validatePass = (rule, value, callback) => {
                if (value === '') {
                    callback(new Error('请输入密码'));
                } else {
                    if (this.registerForm.confirmPwd !== '') {
                        // 对第二个密码框单独验证
                        this.$refs.registerForm.validateField('confirmPwd');
                    }
                    callback();
                }
            };
            const validateConfirmPwd = (rule, value, callback) => {
                if (value === '') {
                    callback(new Error('请再次输入密码'));
                } else if (value !== this.registerForm.pwd) {
                    callback(new Error('两次输入密码不一致!'));
                } else {
                    callback();
                }
            };


            return {
                registerForm: {
                    username: '',
                    pwd: '',
                    confirmPwd: ''
                },
                ruleValidate: {
                    username: [
                        { required: true, message: '账号不能为空', trigger: 'blur' }
                    ],
                    pwd: [
                        { validator: validatePass, trigger: 'blur' }
                    ],
                    confirmPwd: [
                        { validator: validateConfirmPwd, trigger: 'blur' }
                    ]
                }
            }
        }
    }`

**Comment by TangMonk** [comment]
谢谢，明白了

**Comment by iplus26** [comment]
我觉得这里应当把整个form的data都传入进来，才能把表单配置和页面逻辑解耦出来
