### ISSUE TITLE
1.7.0 版本，运行报错："export 'error' was not found in './rule/' 

### ISSUE THREAD

**Issue by BensonDu** [yiminghe/async-validator#46]
在 es/index.js 中引入 import {error} from './rule/'，rule/index.js 中不存在 ~

**Comment by mansonchor** [comment]
+1，pls fix the bug

**Comment by Khafang** [comment]
same problem here

**Comment by chikara-chan** [comment]
element form validator crash down!!!

**Comment by qkveri** [comment]
I have the same problem!

**Comment by jsdmitry** [comment]
+1 This very importantly to me. My project is not building via the webpack.

**Comment by janhoeck** [comment]
Same here!

**Comment by johanbove** [comment]
I got the same issue this morning with the elementFE project.

In file `/src/index.js:
```
import { error } from './rule/';
```
How does this line work when in `/src/rule/index.js` there is no reference ("required call") to include `error`?

**Comment by shangsinian** [comment]
I have the same problem using ant-design

**Comment by lyd600lty** [comment]
影响生产环境，请尽快修复

**Comment by mansonchor** [comment]
this is a major bug~~ some admin can set npm `dist-tag` back to `1.6.9` ?

**Comment by Leopoldthecoder** [comment]
Element is now locking async-validator to 1.6.9:
```bash
npm i element-ui@1.3.6 -S
```

**Comment by mex** [comment]
For those of you struggling with this issue where `async-validator` is a sub-dependency, you might try to run `npm install async-validator@1.6.9` before running `npm install`. This way your dependency should use the existing `v1.6.9` instead of trying to fetch a new version from the registry.

**Comment by yiminghe** [comment]
Sorry for your inconvenience.

1.7.1 fixed.

**Comment by johanbove** [comment]
Thanks for the quick fix! ☯️
