### ISSUE TITLE
add numeric or patch 'number'

### ISSUE THREAD

**Issue by plandem** [yiminghe/async-validator#8]
```
export function isNumeric(n) {
  return !isNaN(parseFloat(n)) && isFinite(n);
}
```

Right now it's not possibly to use numbers as strings.

**Comment by myqianlan** [comment]
input获取到的value一直是string，所以在验证是否是数字的是候一直不通过。
这是我找到的验证数字的代码：
number(value) {
    if (isNaN(value)) {
      return false;
    }
    return typeof (value) === 'number';
  }
请问，如何以正确的姿势使用这个type

**Comment by plandem** [comment]
http://stackoverflow.com/a/1830844

**Comment by yiminghe** [comment]
this library is used for type system (nodejs).

for web input ,you have to normalize http://react-component.github.io/form/examples/overview.html
